/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: virums (https://sketchfab.com/virums)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pika-4abf0b10596544e7bed789c58f809897
Title: Pika
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export function Pika({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('3D/pika.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions['Take 01'].play();
  }, []);
  // Agrega la rotación utilizando useFrame
  useFrame(() => {
    // Ajusta la velocidad de rotación según sea necesario
    group.current.rotation.y += 0.005;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group
              name="Lamp"
              position={[4.065, 1.005, 6.49]}
              rotation={[-0.268, 0.602, 1.931]}
            >
              <group name="Lamp_1" />
            </group>
            <group
              name="Sphere002"
              position={[-0.004, 1.263, 2.668]}
              rotation={[-0.14, -0.056, 0.385]}
              scale={1.457}
            >
              <mesh
                name="Sphere002_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_0.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Sphere002_0_1"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_0_1.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Sphere002_0_2"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_0_2.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Sphere002_1"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_1.geometry}
                material={materials['Material.004']}
              />
              <mesh
                name="Sphere002_2"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_2.geometry}
                material={materials['Material.006']}
              />
              <mesh
                name="Sphere002_3"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_3.geometry}
                material={materials['Material.002']}
              />
              <mesh
                name="Sphere002_4"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_1"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_1.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_2"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_2.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_3"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_3.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_4"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_4.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_5"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_5.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_6"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_6.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_7"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_7.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_8"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_8.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_9"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_9.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_10"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_10.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_11"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_11.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_12"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_12.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_4_13"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_4_13.geometry}
                material={materials['Material.005']}
              />
              <mesh
                name="Sphere002_5"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_5.geometry}
                material={materials['Material.003']}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/pika.glb');
